### PR TITLE
Have another go at IAM permissions for ECR

### PR DESCRIPTION
**Pull request by thebeanogamer**

### CODE REVIEW

**Comment by david-cooke** [comment]
You know hacktoberfest is in october right?

**Comment by thebeanogamer** [comment]
Thanks Dave

**Comment by david-cooke** [comment]
No problem, glad I could help, if you need any help with the calendar in the future, feel free to DM me. :slightly_smiling_face:

**Comment by thebeanogamer** [comment]
😄  Thanks for the help! By the way, did you know you can set a custom profile picture on your GitHub account? It's true! There's a whole support page about it and everything. https://docs.github.com/en/github/setting-up-and-managing-your-github-profile/personalizing-your-profile#changing-your-profile-picture

**Comment by david-cooke** [comment]
I'll be sure to consider it, this git thing is so cool. You can even merge branches without a pull request! They documented the command and everything https://git-scm.com/docs/git-merge

**Pull request merged**
